spring:
  application:
    name: Gateway
  cloud:
    gateway:
      routes:
        - id: api-produto
          uri: http://localhost:8081
          predicates:
            - Path=/produtos/**
        - id: api-usuario
          uri: http://localhost:8082
          predicates:
            - Path=/usuarios/**
        - id: api-venda
          uri: http://localhost:8083
          predicates:
            - Path=/vendas/**


springdoc:
  enable-native-support: true
  api-docs:
    enabled: true
  swagger-ui:
   enabled: true
   path: /swagger-ui.html
   config-url: /v3/api-docs/swagger-config
   urls:
    - url: /produtos/api-docs
      name: Produto
      primaryName: Produto
    - url: /usuarios/api-docs
      name: Usuario
      primaryName: Usuario
    - url: /vendas/api-docs
      name: Vendas
      primaryName: Vendas

server:
  port: 8080

logging:
  level:
    org.springframework.cloud.gateway: DEBUG
    org.springframework.web: DEBUG