spring:
  application:
    name: Gateway
  doc:
    api-docs:
      path: /v3/api-docs
    swagger-ui:
      configUrl: ${server.servlet.contextPath}/v3/api-docs/swagger-config
      url: ${server.servlet.contextPath}/v3/api-docs
      urls:
        - name: Produto
          url: /produtos/api-docs
        - name: Usuario
          url: /usuarios/api-docs
        - name: Vendas
          url: /vendas/api-docs
  cloud:
    gateway:
      routes:
        - id: api-produto
          uri: http://localhost:8081
          predicates:
            - Path=/produtos/**
        - id: api-usuario
          uri: http://localhost:8082
          predicates:
            - Path=/usuarios/**
        - id: api-venda
          uri: http://localhost:8083
          predicates:
            - Path=/vendas/**

server:
  port: 8080

logging:
  level:
    org.springframework.cloud.gateway: DEBUG
    org.springframework.web: DEBUG